### ISSUE TITLE
Hello! Could you create a simple file like readme? Thx! 

### ISSUE THREAD

**Issue by dustinyzr** [Hxyou/PVRNet#1]
THANK YOU for sharing the code about this paper! I have read your paper on AAAI. and I am so  interested in your nice work!

 I am a rookie in deep learning about model retrieval, especially a freshman on pytorch, But I know how to use caffe to train a CNN or other networks like MVCNN. 

But when it comes to pytorch, I don't know how to train the PVRnet. So could you create a simple guidance for freshmen?

The question may include: 
1. How can I achieve input point clouds and images at the same time?
2. How to train and test this network?

Thank you from bottom of my heart !!!

**Comment by Hxyou** [comment]
Thanks for your attention. We will re-organize the code and add the readme in one month!

**Comment by dustinyzr** [comment]
> Thanks for your attention. We will re-organize the code and add the readme in one month!

Sorry to bother you! But I am really looking forward to your update! Thank you!

**Comment by longmalongma** [comment]
> THANK YOU for sharing the code about this paper! I have read your paper on AAAI. and I am so interested in your nice work!
> 
> I am a rookie in deep learning about model retrieval, especially a freshman on pytorch, But I know how to use caffe to train a CNN or other networks like MVCNN.
> 
> But when it comes to pytorch, I don't know how to train the PVRnet. So could you create a simple guidance for freshmen?
> 
> The question may include:
> 
>     1. How can I achieve input point clouds and images at the same time?
> 
>     2. How to train and test this network?
> 
> 
> Thank you from bottom of my heart !!!

can you tell me how to prepare dataset in mvcnn?or can you send me dataset about mvcnn?Think your very much.my email is that:1442342449@qq.com

**Comment by Hxyou** [comment]
Hi guys,

We release our work in a new repository(https://github.com/iMoonLab/PVRNet), including introduction, code and data.

**Comment by Hxyou** [comment]
Hi guy,

Thanks for your attention. We have released our code and data in a new
repository(https://github.com/iMoonLab/PVRNet). Hope it would be helpful
for you.

Best,
Haoxuan

**Comment by longmalongma** [comment]
Think you for your work,I fund those links about data and pretrained ckpt can't download,Beacuse I am in China,google browser is useless.


------------------ 原始邮件 ------------------
发件人: "Haoxuanyou"<notifications@github.com>;
发送时间: 2019年7月15日(星期一) 上午10:10
收件人: "Hxyou/PVRNet"<PVRNet@noreply.github.com>;
抄送: "longma"<1442342449@qq.com>;"Manual"<manual@noreply.github.com>;
主题: Re: [Hxyou/PVRNet] Hello! Could you create a simple file like readme?Thx!  (#1)



Hi guy,
 
 Thanks for your attention. We have released our code and data in a new
 repository(https://github.com/iMoonLab/PVRNet). Hope it would be helpful
 for you.
 
 Best,
 Haoxuan

**Comment by longmalongma** [comment]
Hello,Think your for your work,when I tried to run your code ,I met this problem.can you tell me how to solve this problem?
 raise RuntimeError('Attempting to deserialize object on a CUDA '
 RuntimeError: Attempting to deserialize object on a CUDA device but  torch.cuda.is_available() is False. If you are running on a CPU-only  machine, please use torch.load with map_location='cpu' to map your  storages to the CPU.


------------------ 原始邮件 ------------------
发件人: "Haoxuanyou"<notifications@github.com>;
发送时间: 2019年7月15日(星期一) 上午10:10
收件人: "Hxyou/PVRNet"<PVRNet@noreply.github.com>;
抄送: "longma"<1442342449@qq.com>;"Manual"<manual@noreply.github.com>;
主题: Re: [Hxyou/PVRNet] Hello! Could you create a simple file like readme?Thx!  (#1)



Hi guy,
 
 Thanks for your attention. We have released our code and data in a new
 repository(https://github.com/iMoonLab/PVRNet). Hope it would be helpful
 for you.
 
 Best,
 Haoxuan
